"""embark_diseases.py — Embark DNA テスト由来の追加遺伝子疾患

ユーザー提供の Embark DNA テストレポート（2026 年版）から抽出した、既存の
DISEASE_KB に未収録だった犬の遺伝子疾患を補完するモジュール。

各エントリは DISEASE_KB と同じスキーマ:
  match:       検索パターンの list（英語名・略号・遺伝子記号）
  title:       和文タイトル（英略号 / 遺伝子を併記）
  summary:     概要（〜150 字）
  mechanism:   分子病態（簡潔）
  symptoms:    臨床症状
  inheritance: 遺伝様式
  advice:      飼育・繁殖アドバイス
  severity:    "high" | "medium" | "low" （任意。明示しない場合は自動推定）
  references:  外部リンク

注意:
  - 多くは特定品種（特定 variant）由来。breed-specific な情報は advice に含める。
  - 軽症・無症状型は severity="low" を明示。生命に関わる致死性は "high"。
  - poodle_genetics.py 側で `from embark_diseases import EMBARK_NEW_DISEASES`
    して DISEASE_KB を補完する。
"""

from urllib.parse import quote_plus as _qp


def _g(q: str) -> str:
    return "https://www.google.com/search?q=" + _qp(q + " 犬 遺伝子")


def _wiki(t: str) -> str:
    return "https://ja.wikipedia.org/wiki/Special:Search/" + _qp(t)


EMBARK_NEW_DISEASES = [
    # ============================================================
    # 血液・凝固系
    # ============================================================
    {
        "match": ["hemophilia a", "factor viii", "f8 deficiency", "血友病a"],
        "title": "血友病 A (Hemophilia A / F8)",
        "summary": "X 連鎖性の凝固第 VIII 因子欠損症。オスで重症化しやすく、わずかな外傷でも止血困難になる出血性疾患です。",
        "mechanism": "F8 遺伝子（X 染色体）の変異により凝固第 VIII 因子の合成・機能が低下。内因系凝固カスケードが破綻し、APTT 延長と出血傾向を呈する。",
        "symptoms": "若齢期からの皮下血腫、関節血腫、抜歯・去勢時の止血困難。重症型では生後数か月以内に大出血で命を落とすこともある。",
        "inheritance": "X 連鎖性劣性。オスは半接合（hemizygous）で発症、メスは保因者として伝搬し稀に発症。",
        "advice": "発症犬は外科処置前に必ず第 VIII 因子製剤や新鮮血漿を準備。繁殖はキャリアメスからオスへの伝搬を避けるため、保因者メスを使わないのが原則。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Hemophilia A)", "url": _g("血友病A F8 第VIII因子 ジャーマンシェパード ボクサー")},
        ],
    },
    {
        "match": ["hemophilia b", "factor ix", "f9 deficiency", "血友病b", "クリスマス病"],
        "title": "血友病 B (Hemophilia B / F9 / クリスマス病)",
        "summary": "X 連鎖性の凝固第 IX 因子欠損症。血友病 A と臨床的に類似しますが、補充製剤や検査が異なる別疾患です。",
        "mechanism": "F9 遺伝子（X 染色体）の変異により第 IX 因子が欠損または機能不全。テリア系・ローデシアンリッジバック等で報告。",
        "symptoms": "若齢からの自然出血・関節血腫・術後出血。重症度は変異の種類により幅広い。",
        "inheritance": "X 連鎖性劣性。",
        "advice": "発症犬は手術・外傷時に第 IX 因子製剤または新鮮凍結血漿が必要。繁殖計画には必ず両親の遺伝子検査を。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Hemophilia B)", "url": _g("血友病B F9 クリスマス病 テリア ローデシアン")},
        ],
    },
    {
        "match": ["factor xi deficiency", "f11 deficiency", "第xi因子"],
        "title": "第 XI 因子欠損症 (Factor XI Deficiency / F11)",
        "summary": "凝固第 XI 因子（FXI）の欠損による軽度〜中等度の出血傾向。Kerry Blue Terrier 等で報告されています。",
        "mechanism": "F11 遺伝子変異により第 XI 因子が低下。APTT 軽度延長を示すが、自然出血は通常まれで手術時に出血が問題になる。",
        "symptoms": "外科手術や抜歯後の遅発性出血、鼻出血。日常は無症状のことが多い。",
        "inheritance": "常染色体（不完全）劣性。",
        "advice": "発症犬は外科処置前に新鮮凍結血漿の準備。Kerry Blue Terrier・Pyrenean Mountain Dog 等での繁殖前検査を推奨。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Factor XI)", "url": _g("Factor XI 第11因子欠損 Kerry Blue Terrier")},
        ],
    },
    {
        "match": ["glanzmann", "thrombasthenia", "itga2b", "グランツマン"],
        "title": "グランツマン血小板無力症 I 型 (Glanzmann's Thrombasthenia / ITGA2B)",
        "summary": "血小板表面の GPIIb/IIIa 受容体が機能せず、血小板凝集が著しく障害される重篤な出血性疾患。",
        "mechanism": "ITGA2B（GPIIb）遺伝子の変異により血小板膜糖タンパクが欠損。血小板数は正常だが凝集できず、止血機構が破綻する。Great Pyrenees・Otterhound で報告。",
        "symptoms": "若齢からの粘膜出血（鼻出血・血尿）、皮下血腫、抜歯時の重度出血。",
        "inheritance": "常染色体劣性。",
        "advice": "確定診断には血小板凝集検査と遺伝子検査が必要。発症犬の外科処置は専門施設で。輸血で対応するが完治はしない。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Glanzmann)", "url": _g("グランツマン血小板無力症 ITGA2B Great Pyrenees")},
        ],
    },
    {
        "match": ["bernard-soulier", "bernard soulier", "gp9 ", "ベルナール"],
        "title": "ベルナール・スーリエ症候群 (Bernard-Soulier Syndrome / GP9)",
        "summary": "血小板膜糖タンパク GPIb-IX-V 複合体の異常により血小板が大型化し凝集障害をきたす遺伝性出血性疾患。Cocker Spaniel で報告。",
        "mechanism": "GP9 遺伝子変異により GPIb-IX-V 複合体が組み立てられず、von Willebrand 因子との結合が不可能になる。",
        "symptoms": "巨大血小板、血小板数減少、皮下・粘膜出血傾向。",
        "inheritance": "常染色体劣性。",
        "advice": "確定診断には血液塗抹と遺伝子検査。外科処置時は輸血準備必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Bernard-Soulier)", "url": _g("Bernard-Soulier GP9 Cocker Spaniel 血小板")},
        ],
    },
    {
        "match": ["elliptocytosis", "sptb exon", "楕円赤血球"],
        "title": "犬楕円赤血球症 (Canine Elliptocytosis / SPTB)",
        "summary": "赤血球の形態が楕円形に変化する遺伝性異常。多くは軽度の溶血性貧血を呈しますが無症状のこともあります。",
        "mechanism": "SPTB（β-スペクトリン）遺伝子変異により赤血球膜骨格が脆弱化し、楕円形・変形を生じる。",
        "symptoms": "軽度〜中等度の溶血性貧血、易疲労性。一部は健康診断での偶発所見にとどまる。",
        "inheritance": "常染色体優性または劣性（変異により異なる）。",
        "advice": "重症例では輸血が必要。発症犬の繁殖は推奨されない。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Elliptocytosis)", "url": _g("犬楕円赤血球症 SPTB スペクトリン")},
        ],
    },
    {
        "match": ["thrombopathia", "rasgrp1", "血小板症"],
        "title": "犬血小板症 (Thrombopathia / RASGRP1)",
        "summary": "血小板の機能異常により凝集が低下する遺伝性出血性疾患。American Eskimo Dog・Basset Hound 等で報告。",
        "mechanism": "RASGRP1 遺伝子の変異により血小板内シグナル伝達が破綻し、凝集応答が低下する。",
        "symptoms": "鼻出血・歯肉出血・術後出血。血小板数は正常だが機能が低下しているため出血時間が延長する。",
        "inheritance": "常染色体劣性。",
        "advice": "繁殖前検査推奨。発症犬の外科処置時には新鮮血小板輸血を準備。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Thrombopathia)", "url": _g("Thrombopathia 血小板症 RASGRP1")},
        ],
    },
    {
        "match": ["p2y12", "p2y12 receptor"],
        "title": "P2Y12 受容体血小板異常症 (P2Y12 Receptor Platelet Disorder)",
        "summary": "血小板の ADP 受容体 P2Y12 の機能異常による軽度の出血傾向。発症は軽症で、術前検査で発見されることが多い。",
        "mechanism": "P2RY12 遺伝子変異により血小板の ADP に対する応答が低下し、二次凝集が障害される。",
        "symptoms": "抜歯・避妊手術等での出血延長。日常的な自然出血は少ない。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬の手術時には血小板輸血または DDAVP 投与で対応。日常生活は通常通り。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (P2Y12)", "url": _g("P2Y12 血小板 ADP 受容体 犬")},
        ],
    },
    {
        "match": ["scott syndrome", "tmem16f", "platelet factor x"],
        "title": "スコット症候群 (Scott Syndrome / TMEM16F)",
        "summary": "血小板表面のリン脂質露出に異常をきたし、第 X 因子受容体機能が低下する稀な出血性疾患。German Shepherd で報告。",
        "mechanism": "TMEM16F（ANO6）遺伝子変異により Ca²⁺ 依存性ホスファチジルセリン外膜露出が障害され、凝固プロトロンビナーゼ複合体形成が低下する。",
        "symptoms": "抜歯・避妊手術後の遅発性出血、まれに自然出血。",
        "inheritance": "常染色体劣性。",
        "advice": "外科処置前に専門医と相談。輸血や凝固因子補充で対応。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Scott Syndrome)", "url": _g("Scott Syndrome TMEM16F 犬")},
        ],
    },
    {
        "match": ["prekallikrein", "klkb1"],
        "title": "プレカリクレイン欠損症 (Prekallikrein Deficiency / KLKB1)",
        "summary": "凝固因子プレカリクレインの欠損による検査異常。多くは無症状で、術前 APTT 延長として偶発的に発見されます。",
        "mechanism": "KLKB1 遺伝子変異によりプレカリクレインが欠損し、APTT が延長するが in vivo の出血傾向は乏しい。",
        "symptoms": "通常は無症状。APTT 延長として検出。重度感染や手術時にまれに出血が問題になる。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬の日常生活は通常通り。検査異常の理由を獣医師に説明できるよう結果を共有。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Prekallikrein)", "url": _g("プレカリクレイン欠損 KLKB1 犬")},
        ],
    },
    {
        "match": ["may-hegglin", "may hegglin", "myh9 ", "メイ・ヘグリン"],
        "title": "メイ・ヘグリン異常症 (May-Hegglin Anomaly / MYH9)",
        "summary": "巨大血小板と白血球封入体を特徴とする遺伝性血小板異常症。多くは無症状で、健康診断で偶発的に発見されます。",
        "mechanism": "MYH9（非筋ミオシン重鎖 IIA）遺伝子変異により血小板産生と白血球内ミオシン構造が異常化する。",
        "symptoms": "通常無症状。血小板減少と巨大血小板像で発見。一部に出血傾向。",
        "inheritance": "常染色体優性。",
        "advice": "日常生活に問題はないが、術前検査で血小板減少と判定されないよう結果カードを携帯することを推奨。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (May-Hegglin)", "url": _g("May-Hegglin MYH9 巨大血小板 犬")},
        ],
    },
    {
        "match": ["von willebrand disease type ii", "vwd ii", "vwd2", "type 2 vwd"],
        "title": "フォン・ヴィレブランド病 II 型 (Type II vWD / VWF)",
        "summary": "von Willebrand 因子の機能異常による中等症の出血性疾患。I 型より重症で、ジャーマン・ショートヘアード・ポインター等で報告。",
        "mechanism": "VWF 遺伝子の特定変異により高分子量 von Willebrand 因子（高機能フォーム）が選択的に欠損する。",
        "symptoms": "抜歯・避妊手術時の中等度出血、まれに自然出血。",
        "inheritance": "常染色体（不完全）優性。",
        "advice": "発症犬の手術前は DDAVP・凍結血漿の準備を。Pointer 系の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (vWD Type II)", "url": _g("フォン・ヴィレブランド病 II型 Pointer VWF")},
        ],
    },
    {
        "match": ["von willebrand disease type iii", "vwd iii", "vwd3", "type 3 vwd"],
        "title": "フォン・ヴィレブランド病 III 型 (Type III vWD / VWF)",
        "summary": "von Willebrand 因子が完全欠損する最重症型。スコティッシュ・テリア・チェサピーク・ベイ・レトリーバー等で報告。",
        "mechanism": "VWF 遺伝子の機能欠失変異により VWF タンパクがほぼ完全に欠損。重度の出血傾向。",
        "symptoms": "若齢からの自然出血、抜歯時の大量出血、血尿、関節血腫。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬の生涯にわたる管理が必要。外傷を避ける生活、手術前は凍結血漿準備必須。繁殖から完全に除外。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (vWD Type III)", "url": _g("フォン・ヴィレブランド病 III型 Scottish Terrier VWF")},
        ],
    },

    # ============================================================
    # 神経・脳系
    # ============================================================
    {
        "match": ["alexander disease", "gfap "],
        "title": "アレキサンダー病 (Alexander Disease / GFAP)",
        "summary": "脳白質に異常なローゼンタール線維が蓄積し、進行性の神経症状をきたす致死性疾患。ヒトの古典的 Alexander 病の犬版。",
        "mechanism": "GFAP 遺伝子変異によりアストロサイトに異常タンパク質が蓄積し、白質変性をきたす。",
        "symptoms": "若齢期からの運動失調・けいれん・行動異常・進行性の麻痺。",
        "inheritance": "常染色体優性（ヒトと同じ機序）。",
        "advice": "治療法なし。両親検査による発症犬出生回避が最重要。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Alexander Disease)", "url": _g("アレキサンダー病 GFAP 犬")},
        ],
    },
    {
        "match": ["alaskan husky encephalopathy", "slc19a3"],
        "title": "アラスカン・ハスキー脳症 (Alaskan Husky Encephalopathy / SLC19A3)",
        "summary": "アラスカン・ハスキー特有の若年発症の重症脳症。チアミン輸送障害が原因。",
        "mechanism": "SLC19A3（チアミントランスポーター）遺伝子変異により脳内チアミン取り込みが障害され、エネルギー代謝が破綻する。",
        "symptoms": "生後 6 か月〜2 歳でけいれん・運動失調・意識障害。多くは進行性。",
        "inheritance": "常染色体劣性。",
        "advice": "ヒトのビオチン-チアミン応答性脳症の犬版。高用量ビオチン・チアミン投与で症状改善する例あり。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Alaskan Husky Encephalopathy)", "url": _g("Alaskan Husky Encephalopathy SLC19A3")},
        ],
    },
    {
        "match": ["fucosidosis", "fuca1 "],
        "title": "犬フコシドーシス (Canine Fucosidosis / FUCA1)",
        "summary": "リソソーム酵素 α-フコシダーゼの欠損による進行性蓄積症。English Springer Spaniel で確立。",
        "mechanism": "FUCA1 遺伝子変異により α-L-フコシダーゼが欠損し、フコース含有糖脂質が中枢神経系に蓄積する。",
        "symptoms": "発症は 1〜2 歳。性格変化・運動失調・嚥下困難・けいれんが進行し、3〜5 歳で死亡することが多い。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。英スプリンガースパニエルの繁殖前検査が標準。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Fucosidosis)", "url": _g("Fucosidosis FUCA1 English Springer Spaniel")},
        ],
    },
    {
        "match": ["beta-mannosidosis", "beta mannosidosis", "β-mannosidosis", "manba "],
        "title": "β-マンノシドーシス (β-Mannosidosis / MANBA)",
        "summary": "リソソーム酵素 β-マンノシダーゼ欠損による稀な進行性蓄積症。",
        "mechanism": "MANBA 遺伝子変異により β-マンノシダーゼ活性が低下し、未分解オリゴ糖が組織に蓄積する。",
        "symptoms": "発達遅延・運動失調・進行性の中枢神経症状。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。両親検査による発症犬出生回避が最重要。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (β-Mannosidosis)", "url": _g("β-マンノシドーシス MANBA 犬")},
        ],
    },
    {
        "match": ["lagotto storage disease", "atg4d"],
        "title": "ラゴット蓄積症 (Lagotto Storage Disease / ATG4D)",
        "summary": "ラゴット・ロマニョーロ特有のオートファジー障害による神経蓄積症。",
        "mechanism": "ATG4D 遺伝子変異によりオートファゴソーム形成が障害され、神経細胞に異常物質が蓄積する。",
        "symptoms": "4〜8 か月齢で発症。運動失調・行動変化・進行性神経症状。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。ラゴット・ロマニョーロの繁殖前検査が必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Lagotto Storage)", "url": _g("Lagotto Storage Disease ATG4D")},
        ],
    },
    {
        "match": ["paroxysmal dyskinesia", "pxd ", "pign "],
        "title": "発作性運動異常症 (Paroxysmal Dyskinesia / PIGN)",
        "summary": "意識正常のまま不随意運動の発作を繰り返す疾患。てんかんと混同されがちですが別疾患です。",
        "mechanism": "PIGN 遺伝子変異により GPI アンカー型タンパク質の合成が障害され、神経細胞膜機能が変化する。",
        "symptoms": "数秒〜数分の不随意運動発作。発作中も意識は保たれ、けいれんは伴わない。",
        "inheritance": "常染色体劣性。",
        "advice": "誘発因子（興奮・運動）の回避。一部は薬物治療で頻度低減。生命予後は通常良好。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Paroxysmal Dyskinesia)", "url": _g("発作性運動異常症 PIGN 犬")},
        ],
    },
    {
        "match": ["dental-skeletal-retinal anomaly", "mia3 ", "dsra "],
        "title": "歯・骨格・網膜異常症 (Dental-Skeletal-Retinal Anomaly / MIA3)",
        "summary": "歯のエナメル質、骨格、網膜の発達異常を併発する稀な多臓器症候群。Cane Corso で報告。",
        "mechanism": "MIA3（TANGO1）遺伝子変異によりコラーゲン分泌が障害され、エナメル質形成・骨形成・網膜構造に多臓器異常が生じる。",
        "symptoms": "歯のエナメル質形成不全、骨格変形、進行性網膜萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "Cane Corso ブリーダー向けの新規検査項目。発症犬は歯科ケア・眼科ケアの継続が必要。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (DSRA MIA3)", "url": _g("MIA3 Cane Corso TANGO1 歯 骨格")},
        ],
    },
    {
        "match": ["hereditary cerebellar ataxia", "selenop"],
        "title": "遺伝性小脳失調症 (Hereditary Cerebellar Ataxia / SELENOP)",
        "summary": "Belgian Shepherd 特有の若年発症小脳失調症。セレン代謝の異常が原因です。",
        "mechanism": "SELENOP（セレノタンパク P）遺伝子変異により脳内セレン供給が障害され、小脳プルキンエ細胞が変性する。",
        "symptoms": "生後 6〜12 か月で頭部振戦・運動失調が出現し、数年で重度化。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法は対症療法のみ。Belgian Shepherd（特に Malinois）の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Hereditary Cerebellar Ataxia)", "url": _g("Belgian Shepherd 小脳失調 SELENOP")},
        ],
    },
    {
        "match": ["spinocerebellar ataxia with myokymia", "scn8a ", "kcnj10"],
        "title": "脊髄小脳失調症 + ミオキミア (SCA with Myokymia / KCNJ10)",
        "summary": "Jack Russell Terrier や Smooth-Coated Fox Terrier 等で報告される、運動失調と筋肉の微細な不随意収縮を併発する疾患。",
        "mechanism": "KCNJ10（カリウムチャネル Kir4.1）遺伝子変異により神経興奮性が異常化する。",
        "symptoms": "若齢期からの運動失調、筋線維束の波打つような不随意収縮（ミオキミア）、けいれん。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Jack Russell Terrier 系の繁殖前検査を推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (SCA Myokymia)", "url": _g("脊髄小脳失調 ミオキミア Jack Russell Terrier KCNJ10")},
        ],
    },
    {
        "match": ["spongy degeneration cerebellar ataxia", "atp1b2"],
        "title": "海綿状変性 + 小脳失調 2 型 (Spongy Degeneration with Cerebellar Ataxia 2 / ATP1B2)",
        "summary": "脳白質の海綿状変性を伴う重度の小脳失調症。若齢発症の致死性疾患。",
        "mechanism": "ATP1B2（Na⁺/K⁺ ATPase β2 サブユニット）遺伝子変異により神経細胞のイオンホメオスタシスが破綻する。",
        "symptoms": "新生子期から運動失調・けいれん・進行性の中枢神経症状。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。両親検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Spongy Degeneration)", "url": _g("Spongy Degeneration ATP1B2 犬")},
        ],
    },
    {
        "match": ["shaking puppy syndrome", "plp1", "tremor puppy"],
        "title": "シェイキングパピー症候群 (Shaking Puppy / PLP1)",
        "summary": "英スプリンガースパニエル系の新生子期に発症する全身の振戦症候群。男児（オス）で重症化。",
        "mechanism": "PLP1（プロテオリピドタンパク 1）遺伝子変異により髄鞘形成が障害される。X 連鎖性。",
        "symptoms": "生後 2〜3 週で全身の振戦、起立・哺乳困難。数か月で死亡する例が多い。",
        "inheritance": "X 連鎖性劣性。オスで重症、メスはキャリア。",
        "advice": "治療法なし。英スプリンガースパニエルの繁殖前検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Shaking Puppy)", "url": _g("Shaking Puppy PLP1 English Springer Spaniel")},
        ],
    },
    {
        "match": ["neonatal cerebellar cortical degeneration", "sptbn2", "nccd"],
        "title": "新生子小脳皮質変性症 (Neonatal Cerebellar Cortical Degeneration / SPTBN2)",
        "summary": "Beagle 等の新生子期に発症する重度の小脳変性症。",
        "mechanism": "SPTBN2（β-スペクトリン）遺伝子変異により小脳プルキンエ細胞が変性する。",
        "symptoms": "生後数週から振戦・起立困難・哺乳困難。多くは数か月で死亡。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。Beagle の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (NCCD SPTBN2)", "url": _g("Beagle 小脳皮質変性 SPTBN2")},
        ],
    },
    {
        "match": ["cerebellar hypoplasia", "vldlr ", "小脳低形成"],
        "title": "小脳低形成 (Cerebellar Hypoplasia / VLDLR)",
        "summary": "ユーラシア犬等で報告される、小脳の発達不全による先天性運動失調症。",
        "mechanism": "VLDLR 遺伝子変異により胎児期の小脳形成が障害され、出生時から小脳が低形成となる。",
        "symptoms": "生後すぐから歩行困難・頭部振戦。症状は非進行性で、訓練と環境調整で生活可能。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は安全な環境（滑らない床・段差なし）で QOL を維持可能。寿命は通常通り。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Cerebellar Hypoplasia)", "url": _g("Cerebellar Hypoplasia VLDLR Eurasier")},
        ],
    },
    {
        "match": ["hypomyelination", "tremors", "fnip2"],
        "title": "髄鞘形成不全と振戦 (Hypomyelination and Tremors / FNIP2)",
        "summary": "Weimaraner 特有の中枢神経髄鞘形成不全による若齢振戦症候群。",
        "mechanism": "FNIP2 遺伝子変異により髄鞘合成が遅延・障害される。",
        "symptoms": "生後数週から全身の振戦・運動失調。多くは加齢とともに改善するが完治はしない。",
        "inheritance": "常染色体劣性。",
        "advice": "重症型を除き対症的に経過観察可能。Weimaraner ブリーダーは両親検査を推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Hypomyelination)", "url": _g("Hypomyelination Tremors FNIP2 Weimaraner")},
        ],
    },
    {
        "match": ["demyelinating polyneuropathy", "sbf2 ", "mtrm13"],
        "title": "脱髄性多発神経炎 (Demyelinating Polyneuropathy / SBF2)",
        "summary": "末梢神経の髄鞘が形成不全となり、若齢から進行性の麻痺をきたす遺伝性多発神経炎。",
        "mechanism": "SBF2（MTRM13）遺伝子変異により Schwann 細胞機能が障害され、末梢神経の脱髄が進行する。",
        "symptoms": "幼若期からの四肢の脱力・歩行困難・筋萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。進行性のため徐々に運動機能を失う。早期発見でリハビリにより QOL を保てる。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Demyelinating Polyneuropathy)", "url": _g("脱髄性多発神経炎 SBF2 犬")},
        ],
    },
    {
        "match": ["leonberger polyneuropathy 1", "lpn1", "arhgef10"],
        "title": "レオンベルガー多発性神経炎 1 型 (LPN1 / ARHGEF10)",
        "summary": "Leonberger・Saint Bernard 特有の進行性多発神経炎。若齢〜中年期に発症。",
        "mechanism": "ARHGEF10 遺伝子変異により Schwann 細胞機能が低下し、末梢神経の脱髄が進行する。",
        "symptoms": "後肢から始まる進行性の脱力・運動失調・呼吸障害（喉頭麻痺）。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Leonberger ブリーダーの繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (LPN1)", "url": _g("Leonberger Polyneuropathy LPN1 ARHGEF10")},
        ],
    },
    {
        "match": ["leonberger polyneuropathy 2", "lpn2", "gja9"],
        "title": "レオンベルガー多発性神経炎 2 型 (LPN2 / GJA9)",
        "summary": "Leonberger で報告される 2 番目の多発神経炎遺伝子変異。LPN1 と臨床的に類似。",
        "mechanism": "GJA9（コネキシン）遺伝子変異により神経細胞間ギャップ結合の機能が障害される。",
        "symptoms": "若齢〜中年期からの後肢脱力・運動失調・進行性の四肢麻痺。",
        "inheritance": "常染色体劣性。",
        "advice": "Leonberger では LPN1・LPN2 を併せて検査するのが標準。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (LPN2)", "url": _g("Leonberger LPN2 GJA9")},
        ],
    },
    {
        "match": ["laryngeal paralysis and polyneuropathy", "cntnap1"],
        "title": "喉頭麻痺 + 多発性神経炎 (Laryngeal Paralysis & Polyneuropathy / CNTNAP1)",
        "summary": "Leonberger・Saint Bernard・Labrador で報告される若齢発症の重症多発神経炎・喉頭麻痺症候群。",
        "mechanism": "CNTNAP1 遺伝子変異により末梢神経の有髄線維機能が破綻する。",
        "symptoms": "若齢から呼吸困難（喉頭麻痺）と進行性の四肢麻痺。",
        "inheritance": "常染色体劣性。",
        "advice": "喉頭手術が必要なケースが多い。Leonberger・Labrador での繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Lar Paralysis CNTNAP1)", "url": _g("Laryngeal Paralysis Polyneuropathy CNTNAP1")},
        ],
    },
    {
        "match": ["juvenile laryngeal paralysis", "rab3gap1"],
        "title": "若年性喉頭麻痺 + 多発神経炎 (Juvenile Lar Paralysis / RAB3GAP1)",
        "summary": "Rottweiler 特有の若齢発症の喉頭麻痺と多発神経炎。",
        "mechanism": "RAB3GAP1 遺伝子変異により神経伝達小胞の調節が障害される。",
        "symptoms": "若齢からの吸気性喘鳴・呼吸困難、四肢麻痺。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬には喉頭手術が必要なことが多い。Rottweiler の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Juv Lar Paralysis)", "url": _g("Rottweiler Juvenile Laryngeal Paralysis RAB3GAP1")},
        ],
    },
    {
        "match": ["laryngeal paralysis miniature", "rapgef6"],
        "title": "喉頭麻痺 (Laryngeal Paralysis / RAPGEF6)",
        "summary": "Miniature Bull Terrier の若齢発症喉頭麻痺。",
        "mechanism": "RAPGEF6 遺伝子変異により末梢神経機能が障害される。",
        "symptoms": "若齢期からの吸気性喘鳴・運動不耐性。",
        "inheritance": "常染色体劣性。",
        "advice": "重症例は喉頭披裂軟骨側方化術が適応。Miniature Bull Terrier の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Lar Paralysis RAPGEF6)", "url": _g("Miniature Bull Terrier Laryngeal Paralysis RAPGEF6")},
        ],
    },
    {
        "match": ["alaskan malamute polyneuropathy", "ampn", "ndrg1"],
        "title": "アラスカン・マラミュート多発神経炎 (AMPN / NDRG1)",
        "summary": "Alaskan Malamute 特有の若齢発症進行性多発神経炎。",
        "mechanism": "NDRG1 遺伝子変異により Schwann 細胞機能が低下し、末梢神経の脱髄が進行する。",
        "symptoms": "1〜2 歳での進行性の運動失調・後肢脱力・筋萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Alaskan Malamute の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (AMPN)", "url": _g("Alaskan Malamute Polyneuropathy NDRG1")},
        ],
    },
    {
        "match": ["acral mutilation syndrome", "ams", "gdnf-as"],
        "title": "末端自咬症候群 (Acral Mutilation Syndrome / GDNF-AS)",
        "summary": "感覚神経障害により痛覚を失い、自身の四肢末端を齧り続けてしまう疾患。Spaniel・Pointer 系で報告。",
        "mechanism": "GDNF アンチセンス転写産物の異常により末梢感覚神経が発達不全となり、痛覚・温度覚が失われる。",
        "symptoms": "若齢期からの足先・尾の執拗な自咬、外傷感染、最終的に四肢末端の壊死。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬はエリザベスカラー・物理的保護・行動管理が生涯必要。繁殖前検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Acral Mutilation)", "url": _g("Acral Mutilation Syndrome GDNF Spaniel Pointer")},
        ],
    },

    # ============================================================
    # 眼科系
    # ============================================================
    {
        "match": ["primary lens luxation", "pll", "adamts17"],
        "title": "原発性水晶体脱臼 (Primary Lens Luxation / ADAMTS17)",
        "summary": "水晶体を支える小帯（ツォン小帯）の脆弱化により水晶体が脱臼する、テリア系で頻発する眼科疾患。",
        "mechanism": "ADAMTS17 遺伝子変異により小帯線維が脆弱化し、ほとんどの発症犬で 3〜8 歳頃に水晶体脱臼を生じる。",
        "symptoms": "急性発症の眼痛・視力低下・続発緑内障。早期手術しないと失明することが多い。",
        "inheritance": "常染色体劣性。",
        "advice": "Jack Russell・Miniature Bull Terrier・中国冠毛犬等の繁殖前検査必須。脱臼発生時は緊急眼科受診。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (PLL)", "url": _g("原発性水晶体脱臼 PLL ADAMTS17")},
        ],
    },
    {
        "match": ["primary open angle glaucoma", "poag"],
        "title": "原発性開放隅角緑内障 (POAG / ADAMTS10, ADAMTS17)",
        "summary": "前房隅角の構造異常により眼圧が緩徐に上昇し、視神経が徐々に障害される遺伝性緑内障。",
        "mechanism": "ADAMTS10 / ADAMTS17 等の遺伝子変異により小柱網のコラーゲン構造が脆弱化し、房水流出が低下する。",
        "symptoms": "中年期から徐々に眼圧上昇。早期は無症状で、視神経萎縮が進行してから視力障害が顕在化。",
        "inheritance": "常染色体劣性。",
        "advice": "Beagle・Norwegian Elkhound・Shar-Pei 等で報告。定期的な眼圧測定と眼圧下降薬で進行抑制。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (POAG)", "url": _g("原発性開放隅角緑内障 POAG ADAMTS10")},
        ],
    },
    {
        "match": ["goniodysgenesis", "pld", "olfm3"],
        "title": "前眼房隅角形成不全症 + 緑内障 (Goniodysgenesis / PLD / OLFM3)",
        "summary": "前房隅角の発達異常により房水流出路が狭くなり、続発性閉塞隅角緑内障を起こしやすくなる疾患。",
        "mechanism": "OLFM3 遺伝子変異により胎児期の前房隅角形成が異常となり、線維柱帯の構造が変化する。",
        "symptoms": "中年期からの急性発症緑内障・眼痛・失明。",
        "inheritance": "常染色体劣性または優性。",
        "advice": "Border Collie・Flat-Coated Retriever 等で報告。定期的な眼科検診で早期発見し、ゴニオレンズ検査で隅角評価。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (PLD)", "url": _g("Pectinate Ligament Dysplasia PLD 緑内障")},
        ],
    },
    {
        "match": ["macular corneal dystrophy", "mcd", "chst6"],
        "title": "斑状角膜ジストロフィー (Macular Corneal Dystrophy / CHST6)",
        "summary": "角膜実質に異常な硫酸化ケラタン硫酸が蓄積し、角膜混濁により視力が低下する遺伝性疾患。",
        "mechanism": "CHST6 遺伝子変異により硫酸化酵素が機能不全となり、角膜実質に未硫酸化ケラタン硫酸が蓄積する。",
        "symptoms": "若齢〜中年期からの両眼の角膜混濁、進行性視力低下。",
        "inheritance": "常染色体劣性。",
        "advice": "進行例には角膜移植が選択肢。Labrador・他犬種で報告。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (MCD)", "url": _g("Macular Corneal Dystrophy CHST6")},
        ],
    },
    {
        "match": ["dry eye curly coat", "decs", "fam83h"],
        "title": "ドライアイ・カーリーコート症候群 (DECS / FAM83H)",
        "summary": "Cavalier King Charles Spaniel 特有のドライアイと巻き毛を併発する症候群。",
        "mechanism": "FAM83H 遺伝子変異により涙腺機能と毛包構造が同時に変化する。",
        "symptoms": "生後早期からの涙液分泌低下による慢性角膜炎、巻き毛、エナメル質低形成。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は生涯にわたる人工涙液点眼。Cavalier King Charles Spaniel ブリーダーの繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (DECS)", "url": _g("Cavalier Dry Eye Curly Coat FAM83H")},
        ],
    },
    {
        "match": ["microphthalmia", "rbp4", "小眼球"],
        "title": "先天性小眼球症 (Microphthalmia / RBP4)",
        "summary": "胎児期のビタミン A 輸送障害による眼球発達不全。Soft Coated Wheaten Terrier 等で報告。",
        "mechanism": "RBP4（レチノール結合タンパク）遺伝子変異により胎児期のビタミン A 供給が障害され、眼球が低形成となる。",
        "symptoms": "生後より両眼の眼球が著しく小さい。重症例では視覚機能なし。",
        "inheritance": "常染色体劣性。",
        "advice": "視覚障害犬として育成。Soft Coated Wheaten Terrier の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Microphthalmia)", "url": _g("Microphthalmia RBP4 Wheaten Terrier")},
        ],
    },
    {
        "match": ["retina dysplasia", "optic nerve hypoplasia", "six6"],
        "title": "網膜異形成・視神経低形成 (Retinal Dysplasia / SIX6)",
        "summary": "Golden Retriever 特有の網膜と視神経の発達異常。",
        "mechanism": "SIX6 遺伝子変異により網膜・視神経の発達が障害される。",
        "symptoms": "生後早期からの視覚障害。重症度には個体差がある。",
        "inheritance": "常染色体劣性。",
        "advice": "Golden Retriever の繁殖前検査推奨。発症犬は生涯にわたる眼科ケアが必要。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Retinal Dysplasia SIX6)", "url": _g("Golden Retriever Retinal Dysplasia SIX6")},
        ],
    },
    {
        "match": ["progressive retinal atrophy pra1", "cngb1"],
        "title": "進行性網膜萎縮症 PRA1 (CNGB1)",
        "summary": "CNGB1 遺伝子変異による桿体光受容体の進行性変性。",
        "mechanism": "CNGB1（環状ヌクレオチド依存性チャネル β サブユニット）変異により桿体光受容体機能が破綻する。",
        "symptoms": "中年期からの夜盲、徐々に日中視力低下、最終的に失明。",
        "inheritance": "常染色体劣性。",
        "advice": "進行は緩徐。生活環境を一定に保てば QOL を維持可能。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (PRA1 CNGB1)", "url": _g("PRA1 CNGB1 犬")},
        ],
    },
    {
        "match": ["bardet-biedl", "bardet biedl", "bbs2", "pra bardet"],
        "title": "PRA バルデー・ビードル症候群 (Bardet-Biedl / BBS2)",
        "summary": "Shetland Sheepdog で報告される、進行性網膜萎縮を伴う遺伝性繊毛病。",
        "mechanism": "BBS2 遺伝子変異により細胞内一次繊毛機能が障害され、網膜光受容体が変性する。",
        "symptoms": "若齢からの夜盲、進行性視力低下、ヒトでは肥満・腎機能異常も伴う。",
        "inheritance": "常染色体劣性。",
        "advice": "Shetland Sheepdog の繁殖前検査推奨。失明後も嗅覚と聴覚で生活可能。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (BBS2)", "url": _g("Bardet-Biedl BBS2 Shetland Sheepdog")},
        ],
    },
    {
        "match": ["x-linked progressive retinal atrophy", "xl-pra1", "rpgr"],
        "title": "X 連鎖性進行性網膜萎縮症 (XL-PRA1 / RPGR)",
        "summary": "X 染色体上の RPGR 遺伝子変異による PRA。Husky・Samoyed 等で報告。",
        "mechanism": "RPGR 遺伝子変異により光受容体繊毛機能が障害される。",
        "symptoms": "若齢期からの夜盲、進行性失明。オスで重症、メスは保因者。",
        "inheritance": "X 連鎖性劣性。",
        "advice": "Husky・Samoyed の繁殖前検査推奨（特にオス）。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (XL-PRA1)", "url": _g("X-linked PRA RPGR Husky Samoyed")},
        ],
    },
    {
        "match": ["autosomal dominant pra", "rho ", "ad-pra"],
        "title": "常染色体優性進行性網膜萎縮症 (AD-PRA / RHO)",
        "summary": "ロドプシン遺伝子変異による優性遺伝の進行性網膜萎縮症。1 コピーで発症するため繁殖管理が重要。",
        "mechanism": "RHO 遺伝子変異により桿体光受容体のロドプシンタンパクが異常折りたたみされ、光受容体が変性する。",
        "symptoms": "若齢〜中年期からの夜盲、進行性失明。",
        "inheritance": "常染色体優性。",
        "advice": "P/N でも発症するため、繁殖計画の慎重な選定が必須。Bullmastiff・English Mastiff 等で報告。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (AD-PRA RHO)", "url": _g("常染色体優性PRA RHO ロドプシン Mastiff")},
        ],
    },

    # ============================================================
    # 代謝・内分泌系
    # ============================================================
    {
        "match": ["malignant hyperthermia", "ryr1", "悪性高熱症"],
        "title": "悪性高熱症 (Malignant Hyperthermia / RYR1)",
        "summary": "麻酔薬（特に揮発性麻酔薬）に対する重篤な薬剤反応。代謝亢進と高体温で致死的になる可能性あり。",
        "mechanism": "RYR1（リアノジン受容体）遺伝子変異により骨格筋の Ca²⁺ 放出が異常亢進し、麻酔薬で誘発される過剰な熱産生と代謝亢進を起こす。",
        "symptoms": "全身麻酔中の急激な体温上昇・頻脈・筋強直・代謝性アシドーシス。致死的になることもある。",
        "inheritance": "常染色体優性。",
        "advice": "発症犬の麻酔は禁忌薬剤を避け、必要な場合はダントロレン準備の上で実施。検査結果を必ず獣医師に共有。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Malignant Hyperthermia)", "url": _g("悪性高熱症 RYR1 犬 麻酔")},
        ],
    },
    {
        "match": ["long qt syndrome", "kcnq1", "long-qt"],
        "title": "QT 延長症候群 (Long QT Syndrome / KCNQ1)",
        "summary": "心電図 QT 間隔が延長し、致死的不整脈（多形性心室頻拍）を生じやすくなる遺伝性疾患。",
        "mechanism": "KCNQ1（カリウムチャネル Kv7.1）遺伝子変異により心筋細胞のカリウム電流が低下し、活動電位持続時間が延長する。",
        "symptoms": "失神発作、興奮時の突然死。心電図検査で発見されることが多い。",
        "inheritance": "常染色体優性。",
        "advice": "発症犬は β 遮断薬・ストレス回避による管理。心臓検査結果カードを携帯することを推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Long QT)", "url": _g("QT延長症候群 KCNQ1 犬")},
        ],
    },
    {
        "match": ["polycystic kidney disease", "pkd1", "多発性嚢胞腎"],
        "title": "多発性嚢胞腎 (Polycystic Kidney Disease / PKD1)",
        "summary": "両側腎臓に多数の嚢胞が形成され、加齢とともに腎機能が低下していく疾患。",
        "mechanism": "PKD1（ポリシスチン 1）遺伝子変異により腎尿細管細胞の繊毛機能が障害され、嚢胞形成が進行する。",
        "symptoms": "中年期からの多飲多尿・腎機能低下。進行例では慢性腎不全に至る。",
        "inheritance": "常染色体優性（P/N でも発症リスクあり）。",
        "advice": "発症犬は腎ケア食と定期的な腎機能検査で QOL を維持。繁殖個体には必ず検査を。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (PKD)", "url": _g("多発性嚢胞腎 PKD1 犬")},
        ],
    },
    {
        "match": ["pompe disease", "pompe's", "gaa ", "glycogen storage ii"],
        "title": "ポンペ病 (Pompe Disease / GAA)",
        "summary": "リソソーム酵素 α-グルコシダーゼ欠損による糖原蓄積症 II 型。心筋・骨格筋・神経系に重篤な障害を起こします。",
        "mechanism": "GAA 遺伝子変異により α-グルコシダーゼが欠損し、リソソームにグリコーゲンが蓄積。心筋・骨格筋細胞が機能不全になる。",
        "symptoms": "若齢からの心筋肥大、筋力低下、呼吸困難。多くは数年以内に死亡。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法は対症療法のみ。Lapphund 系の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Pompe)", "url": _g("ポンペ病 GAA Lapphund 犬")},
        ],
    },
    {
        "match": ["primary hyperoxaluria", "agxt", "原発性高シュウ酸尿症"],
        "title": "原発性高シュウ酸尿症 (Primary Hyperoxaluria / AGXT)",
        "summary": "肝臓酵素 AGT の欠損により尿中シュウ酸が異常に増加し、若齢期から重症腎結石をきたす疾患。",
        "mechanism": "AGXT 遺伝子変異により AGT 酵素が機能不全となり、グリオキシル酸がシュウ酸に変換され大量に尿中排泄される。",
        "symptoms": "若齢期からの繰り返す腎結石・腎不全・血尿。多くは進行性で予後不良。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は低シュウ酸食、ビタミン B6 投与、結石除去手術等の包括的管理が必要。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Primary Hyperoxaluria)", "url": _g("原発性高シュウ酸尿症 AGXT 犬")},
        ],
    },
    {
        "match": ["urate kidney", "urate bladder", "slc2a9"],
        "title": "尿酸結石症 (Urate Urolithiasis / SLC2A9)",
        "summary": "尿酸排泄異常により尿路に結石が形成されやすくなる遺伝性疾患。Dalmatian で固定変異。",
        "mechanism": "SLC2A9 遺伝子変異により尿細管での尿酸再吸収が低下し、尿中尿酸濃度が上昇する。HUU と類似。",
        "symptoms": "繰り返す尿路結石、血尿、尿閉。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は低プリン食・十分な水分摂取の生涯管理。Dalmatian は全頭ホモのため標準的に予防食が推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Urate Urolithiasis)", "url": _g("尿酸結石 SLC2A9 Dalmatian")},
        ],
    },
    {
        "match": ["xanthine urolithiasis", "xdh", "キサンチン結石"],
        "title": "キサンチン尿路結石症 (Xanthine Urolithiasis / XDH)",
        "summary": "キサンチンオキシダーゼ欠損により尿中キサンチンが増加し、結石が形成される代謝異常。",
        "mechanism": "XDH 遺伝子変異によりキサンチンが尿酸へ変換されず、難溶性のキサンチンとして尿中に蓄積する。",
        "symptoms": "繰り返す尿路結石、血尿、尿閉。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は低プリン食・水分摂取奨励。アロプリノールは禁忌。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Xanthine Urolithiasis)", "url": _g("キサンチン結石 XDH 犬")},
        ],
    },
    {
        "match": ["2-dha", "2,8-dihydroxyadenine", "aprt", "アデニン"],
        "title": "2,8-ジヒドロキシアデニン尿路結石症 (APRT)",
        "summary": "アデニン代謝酵素欠損により尿中に難溶性の 2,8-DHA 結石が形成される代謝異常。",
        "mechanism": "APRT 遺伝子変異によりアデニンホスホリボシルトランスフェラーゼが欠損し、アデニンが 2,8-DHA に変換される。",
        "symptoms": "繰り返す尿路結石、腎機能障害。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は低プリン食 + アロプリノール投与で結石形成を予防。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (2,8-DHA)", "url": _g("2,8-DHA APRT 結石 犬")},
        ],
    },
    {
        "match": ["protein losing nephropathy", "pln", "nphs1"],
        "title": "蛋白漏出性腎症 (Protein Losing Nephropathy / NPHS1)",
        "summary": "若齢期から尿中に大量のタンパク質が漏出し、進行性に腎機能が低下する疾患。",
        "mechanism": "NPHS1 遺伝子変異により糸球体スリット膜のネフリンタンパクが機能不全となり、タンパク漏出が起こる。",
        "symptoms": "若齢期からの低アルブミン血症、浮腫、進行性腎不全。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は腎ケア食・ACE 阻害薬による管理。早期発見が寿命に直結する。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (PLN)", "url": _g("蛋白漏出性腎症 NPHS1 犬")},
        ],
    },
    {
        "match": ["fanconi syndrome", "fan1", "ファンコニ症候群"],
        "title": "ファンコニ症候群 (Fanconi Syndrome / FAN1)",
        "summary": "Basenji 特有の腎尿細管再吸収障害症候群。グルコース・アミノ酸・電解質が尿中に大量漏出します。",
        "mechanism": "FAN1 遺伝子変異により近位尿細管細胞の機能が広範に障害される。",
        "symptoms": "中年期からの多飲多尿・体重減少・グルコース尿（血糖正常）・アミノ酸尿。進行例で腎不全。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は電解質補正・重炭酸投与で長期管理可能。Basenji の繁殖前検査必須。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Fanconi)", "url": _g("ファンコニ症候群 FAN1 Basenji")},
        ],
    },
    {
        "match": ["x-linked hereditary nephropathy 2", "xlhn", "col4a5"],
        "title": "X 連鎖性遺伝性腎症 (XLHN / COL4A5)",
        "summary": "Samoyed 特有の X 連鎖性 IV 型コラーゲン異常による遺伝性糸球体腎症（Alport 症候群様）。",
        "mechanism": "COL4A5 遺伝子変異により糸球体基底膜の IV 型コラーゲン構造が異常化し、進行性糸球体硬化症をきたす。",
        "symptoms": "オスで若齢発症の蛋白尿・血尿・腎不全。メスは保因者で軽症。",
        "inheritance": "X 連鎖性。",
        "advice": "Samoyed のオス繁殖時に必須検査。発症犬は腎ケア食・ACE 阻害薬。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (XLHN)", "url": _g("X連鎖性遺伝性腎症 COL4A5 Samoyed")},
        ],
    },
    {
        "match": ["diffuse cystic renal dysplasia", "inpp5e", "renal dysplasia hepatic"],
        "title": "嚢胞性腎異形成 + 肝線維症 (Renal Dysplasia / INPP5E)",
        "summary": "Norwich Terrier で報告される、若齢期からの嚢胞性腎異形成と肝線維症を併発する症候群。",
        "mechanism": "INPP5E 遺伝子変異により細胞内一次繊毛機能が障害され、腎・肝の発達異常をきたす。",
        "symptoms": "若齢期からの多飲多尿、腎不全、肝機能異常。",
        "inheritance": "常染色体劣性。",
        "advice": "Norwich Terrier の繁殖前検査推奨。発症犬は腎・肝の早期サポート。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Cystic Renal Dysplasia)", "url": _g("嚢胞性腎異形成 INPP5E Norwich Terrier")},
        ],
    },
    {
        "match": ["congenital hypothyroidism", "tpo ", "slc5a5", "甲状腺機能低下"],
        "title": "先天性甲状腺機能低下症 (Congenital Hypothyroidism / TPO, SLC5A5)",
        "summary": "胎児期から甲状腺ホルモン合成が障害される代謝性疾患。新生子期からの発達遅延が特徴。",
        "mechanism": "TPO（甲状腺ペルオキシダーゼ）または SLC5A5（NIS）遺伝子変異により甲状腺ホルモン合成が障害される。",
        "symptoms": "新生子期からの発達遅延、低身長、巨大舌、慢性便秘、毛量減少。",
        "inheritance": "常染色体劣性。",
        "advice": "早期診断で甲状腺ホルモン補充療法により発達は正常化する。Rat Terrier・Toy Fox Terrier・French Bulldog・Shih Tzu 等で報告。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Congenital Hypothyroidism)", "url": _g("先天性甲状腺機能低下症 TPO SLC5A5 犬")},
        ],
    },
    {
        "match": ["pituitary dwarfism kbd", "pou1f1"],
        "title": "下垂体性小人症 (Pituitary Dwarfism / POU1F1)",
        "summary": "Karelian Bear Dog で報告される、下垂体ホルモン分泌不全症。",
        "mechanism": "POU1F1（Pit-1）遺伝子変異により下垂体前葉細胞の分化が障害され、成長ホルモン・甲状腺刺激ホルモン分泌が低下する。",
        "symptoms": "出生時は正常だが、生後数か月で同腹兄弟との成長差が顕著に。毛量減少も伴う。",
        "inheritance": "常染色体劣性。",
        "advice": "成長ホルモン・甲状腺ホルモンの補充療法で QOL を改善可能。Karelian Bear Dog の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Pituitary Dwarfism)", "url": _g("下垂体性小人症 POU1F1 Karelian Bear Dog")},
        ],
    },
    {
        "match": ["proportionate dwarfism", "gh1 ", "growth hormone"],
        "title": "比例性小人症 (Proportionate Dwarfism / GH1)",
        "summary": "成長ホルモン欠損により体全体が均整を保ったまま小さくなる先天性疾患。Chihuahua で報告。",
        "mechanism": "GH1（成長ホルモン）遺伝子変異により成長ホルモン分泌が低下する。",
        "symptoms": "生後数か月で同腹兄弟より小さく、体格は均整がとれている。代謝・繁殖は影響を受ける。",
        "inheritance": "常染色体劣性。",
        "advice": "GH 補充療法で改善可能だが高コスト。Chihuahua の繁殖前検査推奨。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Proportionate Dwarfism)", "url": _g("Proportionate Dwarfism GH1 Chihuahua")},
        ],
    },
    {
        "match": ["disproportionate dwarfism", "prkg2"],
        "title": "不均衡性小人症 (Disproportionate Dwarfism / PRKG2)",
        "summary": "Dogo Argentino で報告される、四肢が体幹に比して短い不均衡性小人症。",
        "mechanism": "PRKG2 遺伝子変異により骨成長板の軟骨細胞分化が障害される。",
        "symptoms": "生後早期から四肢の発達遅延・短肢化。寿命と全身代謝には影響少ない。",
        "inheritance": "常染色体劣性。",
        "advice": "Dogo Argentino ブリーダーの繁殖前検査推奨。発症犬は関節炎の予防的管理を。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Disprop Dwarfism)", "url": _g("Dogo Argentino Disproportionate Dwarfism PRKG2")},
        ],
    },
    {
        "match": ["bully whippet", "mstn", "ミオスタチン"],
        "title": "ブリーウィペット症候群 (Bully Whippet / MSTN)",
        "summary": "ミオスタチン遺伝子変異により骨格筋量が異常に増加する Whippet 特有の形質。重度型では関節障害をきたす。",
        "mechanism": "MSTN 遺伝子変異により筋成長を抑制するミオスタチンタンパクが機能低下し、筋線維数が増加する。",
        "symptoms": "重度型では極端な筋肥大、関節障害、運動制限。軽度型（ヘテロ）はスピード向上のみで健康に問題なし。",
        "inheritance": "常染色体（不完全）優性。ヘテロは健康、ホモは重症。",
        "advice": "Whippet レース界では heterozygous（ヘテロ）が有利とされるが、ホモ × ホモは厳禁。繁殖計画に必須。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Bully Whippet)", "url": _g("Bully Whippet MSTN ミオスタチン")},
        ],
    },
    {
        "match": ["medium-chain acyl-coa", "mcadd", "acadm"],
        "title": "中鎖アシル CoA 脱水素酵素欠損症 (MCADD / ACADM)",
        "summary": "脂肪酸 β 酸化障害により、絶食時の低血糖発作をきたす代謝性疾患。Cavalier King Charles Spaniel で報告。",
        "mechanism": "ACADM 遺伝子変異により中鎖脂肪酸の β 酸化が障害され、絶食時のエネルギー供給が破綻する。",
        "symptoms": "若齢期からの絶食誘発性の低血糖発作・嘔吐・意識障害。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は頻回の少量給餌で低血糖を予防。Cavalier KC ブリーダーの繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (MCADD)", "url": _g("MCADD ACADM Cavalier 犬")},
        ],
    },
    {
        "match": ["pyruvate dehydrogenase deficiency", "pdp1"],
        "title": "ピルビン酸脱水素酵素複合体欠損症 (PDH Deficiency / PDP1)",
        "summary": "Spaniel 系で報告される、糖代謝中核酵素の欠損による代謝性脳症。",
        "mechanism": "PDP1 遺伝子変異によりピルビン酸脱水素酵素複合体の活性化が障害され、エネルギー代謝が破綻する。",
        "symptoms": "若齢期からの運動失調・けいれん・乳酸アシドーシス。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は高脂肪・低炭水化物食、ケトジェニック食で症状緩和。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (PDH Deficiency)", "url": _g("PDH PDP1 Spaniel 犬")},
        ],
    },
    {
        "match": ["hypocatalasia", "acatalasemia", "cat gene", "カタラーゼ"],
        "title": "低カタラーゼ血症 (Acatalasemia / CAT)",
        "summary": "カタラーゼ酵素欠損による無症状〜軽症の代謝異常。健康診断で発見されることが多い。",
        "mechanism": "CAT 遺伝子変異によりカタラーゼ活性が著しく低下するが、補完経路により多くは無症状で経過する。",
        "symptoms": "通常無症状。重度例で口腔内潰瘍・歯肉炎を生じることがある。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は口腔ケアを徹底。検査結果カードを保管し、不要な不安を避ける。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Acatalasemia)", "url": _g("低カタラーゼ血症 アカタラセミア 犬")},
        ],
    },
    {
        "match": ["hereditary vitamin d resistant", "vdr ", "vitamin d resistant rickets"],
        "title": "ビタミン D 抵抗性くる病 (Vitamin D-Resistant Rickets / VDR)",
        "summary": "ビタミン D 受容体の機能異常により骨の石灰化が障害される若年発症の骨疾患。",
        "mechanism": "VDR 遺伝子変異によりビタミン D 受容体が機能不全となり、カルシウム・リン代謝が破綻し、骨石灰化が進まない。",
        "symptoms": "若齢期からの骨格変形、骨折、低カルシウム血症、てんかん発作。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は活性型ビタミン D・カルシウム補充療法。早期治療で骨格成長を改善可能。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (VDR Rickets)", "url": _g("ビタミンD抵抗性くる病 VDR 犬")},
        ],
    },
    {
        "match": ["hypophosphatasia", "alpl ", "アルカリホスファターゼ"],
        "title": "低アルカリホスファターゼ症 (Hypophosphatasia / ALPL)",
        "summary": "Karelian Bear Dog で報告される、アルカリホスファターゼ欠損による骨石灰化障害。",
        "mechanism": "ALPL 遺伝子変異により組織非特異的アルカリホスファターゼが欠損し、骨の石灰化過程が破綻する。",
        "symptoms": "若齢期からの骨格異常、骨折、歯の異常脱落。",
        "inheritance": "常染色体劣性。",
        "advice": "Karelian Bear Dog ブリーダーの繁殖前検査推奨。発症犬は骨整形外科的管理が必要。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Hypophosphatasia)", "url": _g("低アルカリホスファターゼ症 ALPL 犬")},
        ],
    },
    {
        "match": ["alt activity", "gpt activity"],
        "title": "ALT 活性遺伝マーカー (ALT Activity / GPT)",
        "summary": "血清 ALT 活性（肝酵素）のベースライン値を決定する遺伝マーカー。疾患ではなく解釈補助の参考情報です。",
        "mechanism": "GPT（ALT 遺伝子）の SNP により血清 ALT 活性のベースラインが個体間で異なる。",
        "symptoms": "症状なし。健康診断で ALT 値が高め・低めに出る場合の解釈の参考になる。",
        "inheritance": "GPT SNP は遺伝するが、疾患ではない。",
        "advice": "ALT 結果のベースライン値理解に役立つ補助情報。健康診断での過剰評価・過小評価を防ぐ。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (ALT Activity)", "url": _g("ALT 活性 GPT 犬 遺伝子マーカー")},
        ],
    },
    {
        "match": ["succinic semialdehyde dehydrogenase", "aldh5a1", "ssadh"],
        "title": "コハク酸セミアルデヒド脱水素酵素欠損症 (SSADH / ALDH5A1)",
        "summary": "Saluki で報告される、GABA 代謝の遺伝性異常による神経代謝障害。",
        "mechanism": "ALDH5A1 遺伝子変異により γ-ヒドロキシ酪酸が脳内に蓄積し、神経機能が障害される。",
        "symptoms": "若齢期からの精神運動発達遅延・運動失調・てんかん発作。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は対症療法。Saluki の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (SSADH)", "url": _g("コハク酸セミアルデヒド SSADH ALDH5A1 Saluki")},
        ],
    },
    {
        "match": ["intestinal lipid malabsorption", "acsl5", "脂質吸収不良"],
        "title": "腸管脂質吸収不良症 (Intestinal Lipid Malabsorption / ACSL5)",
        "summary": "Australian Kelpie で報告される、長鎖脂肪酸の腸吸収障害。",
        "mechanism": "ACSL5 遺伝子変異により腸上皮細胞での長鎖脂肪酸活性化が障害され、吸収が低下する。",
        "symptoms": "若齢期からの慢性下痢・体重減少・成長不良。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は中鎖脂肪酸を主体とする低脂肪食で症状改善。Australian Kelpie の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Intestinal Lipid)", "url": _g("Intestinal Lipid Malabsorption ACSL5 Kelpie")},
        ],
    },
    {
        "match": ["inflammatory myopathy", "slc25a12"],
        "title": "炎症性ミオパチー (Inflammatory Myopathy / SLC25A12)",
        "summary": "若齢期から筋線維の炎症と変性をきたす遺伝性筋疾患。",
        "mechanism": "SLC25A12（ミトコンドリアアスパラギン酸/グルタミン酸キャリア）遺伝子変異により筋細胞のエネルギー代謝が破綻する。",
        "symptoms": "若齢期からの筋力低下・運動不耐性・筋萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。免疫抑制療法は無効。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Inflammatory Myopathy)", "url": _g("Inflammatory Myopathy SLC25A12 犬")},
        ],
    },
    {
        "match": ["anhidrotic ectodermal dysplasia", "eda ", "外胚葉異形成"],
        "title": "無汗性外胚葉異形成症 (Anhidrotic Ectodermal Dysplasia / EDA)",
        "summary": "汗腺・毛包・歯の発達不全をきたす遺伝性外胚葉性疾患。X 連鎖性。",
        "mechanism": "EDA 遺伝子（X 連鎖）変異により外胚葉由来組織の発達が障害される。",
        "symptoms": "毛量減少、汗腺欠損による体温調節障害、歯の欠損・形成異常。",
        "inheritance": "X 連鎖性劣性。オスで重症、メスはモザイクとして部分発症することがある。",
        "advice": "発症犬は高温環境を避け、歯科ケアを徹底。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Anhidrotic Ectodermal)", "url": _g("無汗性外胚葉異形成症 EDA 犬")},
        ],
    },

    # ============================================================
    # 皮膚・被毛系
    # ============================================================
    {
        "match": ["oculocutaneous albinism", "oca", "slc45a2", "アルビニズム"],
        "title": "眼皮膚白皮症 (Oculocutaneous Albinism / SLC45A2)",
        "summary": "Bullmastiff 等で報告される、メラニン合成酵素異常による真性白皮症。視覚障害を伴います。",
        "mechanism": "SLC45A2 遺伝子変異によりメラノサイトでのチロシン代謝が障害され、メラニン合成が低下する。",
        "symptoms": "出生時から被毛・皮膚が白く、虹彩が淡色〜赤目、羞明、視力低下。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は紫外線回避・遮光保護・皮膚定期検診。繁殖は倫理的に推奨されない。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (OCA SLC45A2)", "url": _g("眼皮膚白皮症 SLC45A2 Bullmastiff")},
        ],
    },
    {
        "match": ["congenital cornification disorder", "nsdhl", "角化異常"],
        "title": "先天性角化異常症 (Congenital Cornification Disorder / NSDHL)",
        "summary": "Chihuahua で報告される、表皮角化過程の異常による皮膚疾患。",
        "mechanism": "NSDHL 遺伝子変異によりコレステロール合成過程が障害され、表皮角化が異常化する。",
        "symptoms": "若齢期からの全身性鱗屑、苔癬様皮疹、脱毛。",
        "inheritance": "X 連鎖性。",
        "advice": "発症犬は保湿スキンケア・抗炎症療法で QOL を維持。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (NSDHL)", "url": _g("Congenital Cornification NSDHL Chihuahua")},
        ],
    },
    {
        "match": ["lethal acrodermatitis", "lad mkln", "mkln1"],
        "title": "致死性肢端皮膚炎 (Lethal Acrodermatitis / MKLN1)",
        "summary": "Bull Terrier 特有の四肢末端の重症皮膚炎と発達不全。多くは数年以内に死亡。",
        "mechanism": "MKLN1 遺伝子変異により亜鉛代謝が障害され、皮膚・免疫系の発達が破綻する。",
        "symptoms": "生後数か月からの四肢末端の角化異常、繰り返す感染、発達遅延。",
        "inheritance": "常染色体劣性。",
        "advice": "亜鉛補充等で症状改善は限定的。Bull Terrier ブリーダーの繁殖前検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Lethal Acrodermatitis)", "url": _g("Lethal Acrodermatitis MKLN1 Bull Terrier")},
        ],
    },
    {
        "match": ["dystrophic epidermolysis bullosa", "deb", "col7a1"],
        "title": "栄養障害型表皮水疱症 (DEB / COL7A1)",
        "summary": "皮膚基底膜の VII 型コラーゲン欠損により軽い摩擦でも水疱・潰瘍が生じる重症皮膚疾患。",
        "mechanism": "COL7A1 遺伝子変異により基底膜の係留線維が形成されず、皮膚剥離が起こる。",
        "symptoms": "出生時からの全身性水疱・潰瘍、口腔粘膜病変、感染。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は無刺激ケア・感染予防が必須。Central Asian Shepherd・Golden Retriever 等で報告。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (DEB)", "url": _g("栄養障害型表皮水疱症 DEB COL7A1 犬")},
        ],
    },
    {
        "match": ["junctional epidermolysis bullosa", "jeb", "lama3", "lamb3"],
        "title": "接合部型表皮水疱症 (JEB / LAMA3, LAMB3)",
        "summary": "皮膚基底膜のラミニン異常による重症水疱性皮膚疾患。Australian Cattle Dog・Australian Shepherd で報告。",
        "mechanism": "LAMA3 / LAMB3 遺伝子変異によりラミニン 332 が形成されず、表皮真皮接合部が脆弱化する。",
        "symptoms": "出生時からの全身性水疱・剥離、感染、発達不全。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は無刺激ケアと感染予防、生命予後は通常不良。両親検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (JEB)", "url": _g("接合部型表皮水疱症 JEB LAMA3 犬")},
        ],
    },
    {
        "match": ["ehlers-danlos", "ehlers danlos", "eds", "adamts2", "col5a1"],
        "title": "エーラス・ダンロス症候群 (Ehlers-Danlos / ADAMTS2, COL5A1)",
        "summary": "皮膚の異常な伸展性・脆弱化を特徴とする結合組織異常症。Doberman・Labrador 等で報告。",
        "mechanism": "ADAMTS2（コラーゲンプロセシング酵素）または COL5A1（V 型コラーゲン）の変異により真皮コラーゲンが構造異常化する。",
        "symptoms": "軽微な外傷で皮膚が裂け、関節過伸展、容易にあざが生じる。",
        "inheritance": "常染色体優性または劣性（亜型による）。",
        "advice": "発症犬は外傷を避ける生活設計、術後の縫合困難に注意。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Ehlers-Danlos)", "url": _g("Ehlers-Danlos Syndrome ADAMTS2 犬")},
        ],
    },
    {
        "match": ["darier disease", "atp2a2", "ダリエ"],
        "title": "ダリエ病 (Darier Disease / ATP2A2)",
        "summary": "Irish Terrier で報告される、表皮角化異常による遺伝性皮膚疾患。",
        "mechanism": "ATP2A2（SERCA2）遺伝子変異により角化細胞内 Ca²⁺ ホメオスタシスが破綻し、表皮の脱接着が起こる。",
        "symptoms": "若齢期からの皮膚乳頭状角化・落屑・痒み。皮膚感染を起こしやすい。",
        "inheritance": "常染色体優性。",
        "advice": "発症犬は保湿・抗菌スキンケア。Irish Terrier ブリーダーの繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Darier)", "url": _g("ダリエ病 ATP2A2 Irish Terrier")},
        ],
    },
    {
        "match": ["pachyonychia congenita", "krt16"],
        "title": "先天性爪甲肥厚症 (Pachyonychia Congenita / KRT16)",
        "summary": "Dogue de Bordeaux で報告される、爪と肉球の角化異常。",
        "mechanism": "KRT16（ケラチン 16）遺伝子変異により角化細胞のサイトケラチンネットワークが異常化する。",
        "symptoms": "爪の肥厚・変形、肉球の角化、歩行時の痛み。",
        "inheritance": "常染色体優性。",
        "advice": "発症犬は爪のトリミング・肉球保湿で QOL 維持。Dogue de Bordeaux の繁殖前検査推奨。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Pachyonychia)", "url": _g("Pachyonychia Congenita KRT16 Dogue de Bordeaux")},
        ],
    },
    {
        "match": ["skin fragility syndrome", "pkp1", "皮膚脆弱"],
        "title": "皮膚脆弱症候群 (Skin Fragility Syndrome / PKP1)",
        "summary": "Chesapeake Bay Retriever で報告される、デスモソーム異常による皮膚脆弱化。",
        "mechanism": "PKP1（プラコフィリン 1）遺伝子変異により角化細胞間接着が脆弱化し、軽微な外力で皮膚剥離が起こる。",
        "symptoms": "若齢期からの皮膚水疱・潰瘍・脱毛、発達不全。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は無刺激ケアと感染予防。Chesapeake Bay Retriever ブリーダーの繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Skin Fragility)", "url": _g("Skin Fragility PKP1 Chesapeake")},
        ],
    },
    {
        "match": ["enamel hypoplasia", "enam ", "エナメル質"],
        "title": "エナメル質形成不全 (Enamel Hypoplasia / ENAM)",
        "summary": "歯のエナメル質の薄化・形成不全。Italian Greyhound・Parson Russell Terrier 等で報告。",
        "mechanism": "ENAM（エナメリン）遺伝子変異によりエナメル基質形成が障害される。",
        "symptoms": "永久歯の表面が薄く着色、虫歯・歯髄炎を起こしやすい。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は徹底した歯科ケア、定期的なスケーリング。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Enamel Hypoplasia)", "url": _g("Enamel Hypoplasia ENAM 犬")},
        ],
    },
    {
        "match": ["bald thigh syndrome", "igfbp5"],
        "title": "腿無毛症候群 (Bald Thigh Syndrome / IGFBP5)",
        "summary": "Greyhound・Whippet 等のサイトハウンドで頻発する大腿部脱毛症。",
        "mechanism": "IGFBP5 遺伝子変異により毛包成長因子シグナル伝達が変化し、大腿部の毛包成長が停止する。",
        "symptoms": "両側性大腿部の対称性脱毛。皮膚は健康で痒みなし。",
        "inheritance": "常染色体劣性。",
        "advice": "美容的問題のみで健康への影響なし。寒冷地では保温衣推奨。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (Bald Thigh)", "url": _g("Bald Thigh Syndrome Greyhound IGFBP5")},
        ],
    },

    # ============================================================
    # 筋・運動系
    # ============================================================
    {
        "match": ["muscular dystrophy dmd", "duchenne", "dmd ", "デュシェンヌ"],
        "title": "X 連鎖性筋ジストロフィー (DMD / Duchenne 型)",
        "summary": "ジストロフィン遺伝子変異による進行性筋萎縮症。ヒトの Duchenne 型筋ジストロフィーに相当。",
        "mechanism": "DMD（X 連鎖）遺伝子変異によりジストロフィンタンパクが欠損し、筋細胞膜の力学的安定性が破綻する。",
        "symptoms": "若齢期からの進行性筋萎縮、運動不耐性、心筋症、最終的に呼吸不全。",
        "inheritance": "X 連鎖性劣性。オスで発症、メスは保因者。",
        "advice": "Cavalier KCS・Golden Retriever 等で報告。発症犬の生命予後は厳しい。繁殖時保因者メス除外が標準。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (DMD)", "url": _g("X連鎖性筋ジストロフィー DMD デュシェンヌ 犬")},
        ],
    },
    {
        "match": ["muscular dystrophy dystroglycanopathy", "large1"],
        "title": "ジストログリカン異常症 (Dystroglycanopathy / LARGE1)",
        "summary": "Labrador で報告される、α-ジストログリカンのグリコシル化異常による筋ジストロフィー。",
        "mechanism": "LARGE1 遺伝子変異により α-ジストログリカンが正常に糖鎖修飾されず、筋細胞外基質との結合が破綻する。",
        "symptoms": "若齢期からの筋力低下、運動不耐性、進行性筋萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "Labrador ブリーダーの繁殖前検査推奨。発症犬は対症療法。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Dystroglycanopathy)", "url": _g("Dystroglycanopathy LARGE1 Labrador")},
        ],
    },
    {
        "match": ["ullrich congenital muscular dystrophy", "col6a3", "col6a1"],
        "title": "ウルリッヒ型先天性筋ジストロフィー (UCMD / COL6A1, COL6A3)",
        "summary": "VI 型コラーゲンの構造異常による先天性筋ジストロフィー。Labrador・Landseer で報告。",
        "mechanism": "COL6A1 / COL6A3 遺伝子変異により筋細胞外基質の VI 型コラーゲン構造が異常化する。",
        "symptoms": "出生時または早期からの筋力低下、関節拘縮、運動不耐性。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。発症犬は理学療法で QOL 維持。Labrador・Landseer の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (UCMD)", "url": _g("Ullrich先天性筋ジストロフィー COL6A 犬")},
        ],
    },
    {
        "match": ["congenital muscular dystrophy", "lama2", "merosin"],
        "title": "メロシン欠損型先天性筋ジストロフィー (LAMA2)",
        "summary": "Italian Greyhound 等で報告される、ラミニン α2（メロシン）欠損による先天性筋ジストロフィー。",
        "mechanism": "LAMA2 遺伝子変異によりラミニン α2 が欠損し、筋細胞外基質-基底膜接続が破綻する。",
        "symptoms": "出生時からの筋力低下、関節拘縮、運動発達遅延。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Italian Greyhound ブリーダーの繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (LAMA2 MD)", "url": _g("メロシン欠損 先天性筋ジストロフィー LAMA2 Italian Greyhound")},
        ],
    },
    {
        "match": ["nemaline myopathy", "neb ", "ネマリン"],
        "title": "ネマリンミオパチー (Nemaline Myopathy / NEB)",
        "summary": "American Bulldog で報告される、筋線維にネマリン小体を伴うミオパチー。",
        "mechanism": "NEB（ネブリン）遺伝子変異により筋節構造が異常化する。",
        "symptoms": "若齢期からの筋力低下・運動不耐性・呼吸障害。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。American Bulldog の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Nemaline)", "url": _g("Nemaline Myopathy NEB American Bulldog")},
        ],
    },
    {
        "match": ["inherited myopathy great dane", "bin1"],
        "title": "グレートデーン遺伝性ミオパチー (BIN1)",
        "summary": "Great Dane 特有の若齢発症ミオパチー。",
        "mechanism": "BIN1 遺伝子変異により筋細胞 T-tubule 形成が異常化する。",
        "symptoms": "若齢期からの後肢脱力・運動不耐性・筋萎縮。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Great Dane ブリーダーの繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (BIN1 Myopathy)", "url": _g("Great Dane Inherited Myopathy BIN1")},
        ],
    },
    {
        "match": ["x-linked myotubular myopathy", "xlmtm", "mtm1"],
        "title": "X 連鎖性ミオチュブラーミオパチー (XLMTM / MTM1)",
        "summary": "Labrador で報告される、X 連鎖性ミオパチー。",
        "mechanism": "MTM1 遺伝子変異により筋細胞の T-tubule 構造が異常化する。",
        "symptoms": "オスでは若齢からの重度筋力低下、呼吸障害、多くは早期死亡。",
        "inheritance": "X 連鎖性劣性。",
        "advice": "Labrador の繁殖時に保因者メスを避ける。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (XLMTM)", "url": _g("X連鎖性ミオチュブラー MTM1 Labrador")},
        ],
    },
    {
        "match": ["musladin-lueke", "musladin lueke", "mls", "adamtsl2"],
        "title": "マスラディン・ルーク症候群 (MLS / ADAMTSL2)",
        "summary": "Beagle 特有の結合組織異常症。厚い皮膚、関節拘縮、特徴的な顔貌を呈する。",
        "mechanism": "ADAMTSL2 遺伝子変異により細胞外マトリックス組織化が異常化する。",
        "symptoms": "若齢期からの皮膚硬化、関節拘縮、つま先歩行、特徴的顔貌。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬の生命予後は良好。理学療法で関節可動域を維持。Beagle の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (MLS)", "url": _g("Musladin-Lueke MLS ADAMTSL2 Beagle")},
        ],
    },
    {
        "match": ["fetal-onset neonatal neuroaxonal dystrophy", "fnad", "mfn2"],
        "title": "胎児発症型新生子神経軸索ジストロフィー (FNAD / MFN2)",
        "summary": "Giant Schnauzer 特有の胎児期発症の重症神経軸索ジストロフィー。",
        "mechanism": "MFN2（ミトコンドリア融合タンパク）遺伝子変異により神経細胞ミトコンドリア機能が破綻する。",
        "symptoms": "新生子期からの重度の運動失調・神経症状、多くは数か月で死亡。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。Giant Schnauzer の繁殖前検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (FNAD)", "url": _g("Giant Schnauzer FNAD MFN2")},
        ],
    },
    {
        "match": ["myasthenia gravis-like", "chrne heideterrier"],
        "title": "重症筋無力症様症候群 (Myasthenia Gravis-Like / CHRNE)",
        "summary": "Heideterrier 特有の神経筋接合部疾患。重症筋無力症に類似した臨床像。",
        "mechanism": "CHRNE 遺伝子変異により神経筋接合部の ACh 受容体機能が低下する。",
        "symptoms": "若齢期からの易疲労性、運動誘発性脱力。",
        "inheritance": "常染色体劣性。",
        "advice": "コリンエステラーゼ阻害薬で症状緩和。Heideterrier の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (MG-Like CHRNE)", "url": _g("Heideterrier Myasthenia CHRNE")},
        ],
    },
    {
        "match": ["congenital dyserythropoietic anemia and polymyopathy", "cdap", "ehpb1l1"],
        "title": "先天性赤血球異形成貧血 + ミオパチー (CDA-PM / EHBP1L1)",
        "summary": "Labrador で報告される、貧血と筋疾患を併発する稀な複合症候群。",
        "mechanism": "EHBP1L1 遺伝子変異により赤血球と筋細胞の細胞骨格が同時に異常化する。",
        "symptoms": "若齢期からの貧血・筋力低下・運動不耐性。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Labrador の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (CDA-PM)", "url": _g("Labrador CDA Polymyopathy EHBP1L1")},
        ],
    },

    # ============================================================
    # 心臓系
    # ============================================================
    {
        "match": ["cardiomyopathy and juvenile mortality", "cjm", "yars2"],
        "title": "心筋症 + 若年突然死症候群 (CJM / YARS2)",
        "summary": "若齢期に心筋症と突然死をきたす遺伝性ミトコンドリア病。",
        "mechanism": "YARS2（ミトコンドリアアミノアシル tRNA 合成酵素）遺伝子変異によりミトコンドリアタンパク質合成が障害される。",
        "symptoms": "若齢期からの心機能低下、不整脈、運動時の突然死。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は心臓検査と運動制限。繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (CJM)", "url": _g("Cardiomyopathy Juvenile Mortality YARS2")},
        ],
    },
    {
        "match": ["dilated cardiomyopathy", "dcm", "rbm20", "pdk4", "ttn schnauzer"],
        "title": "拡張型心筋症 (DCM / RBM20, PDK4, TTN)",
        "summary": "心室拡張と収縮力低下を特徴とする心筋症。複数の遺伝子変異が関与し、Doberman・Schnauzer・Boxer 等で報告。",
        "mechanism": "RBM20 / PDK4 / TTN 等の心筋特異的遺伝子変異により心筋細胞のエネルギー代謝・収縮機能が破綻する。",
        "symptoms": "中年期からの心拡大・不整脈・うっ血性心不全・運動不耐性。",
        "inheritance": "常染色体優性（多くは不完全浸透）。",
        "advice": "繁殖個体には心臓検査と遺伝子検査の両方を実施。早期発見で ACE 阻害薬・β 遮断薬等の延命治療が可能。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (DCM)", "url": _g("拡張型心筋症 DCM Doberman Schnauzer 犬")},
        ],
    },
    {
        "match": ["neonatal interstitial lung disease", "lamp3", "新生子間質性肺"],
        "title": "新生子間質性肺疾患 (NILD / LAMP3)",
        "summary": "新生子期に発症する間質性肺疾患。多くは数か月以内に死亡。",
        "mechanism": "LAMP3 遺伝子変異により II 型肺胞上皮細胞のリソソーム機能が障害され、肺サーファクタント代謝が破綻する。",
        "symptoms": "新生子期からの進行性呼吸困難、低酸素血症、肺線維化。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。両親検査による発症犬出生回避が最重要。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (NILD)", "url": _g("新生子間質性肺疾患 LAMP3 犬")},
        ],
    },

    # ============================================================
    # その他
    # ============================================================
    {
        "match": ["intervertebral disc disease type i", "fgf4 retrogene cfa12", "ivdd type i"],
        "title": "椎間板疾患 I 型 (IVDD Type I / FGF4 CFA12)",
        "summary": "12 番染色体上の FGF4 レトロジーン挿入による椎間板変性疾患。CDDY と異なる別の FGF4 変異。",
        "mechanism": "12 番染色体（CFA12）への FGF4 レトロジーン挿入により椎間板髄核が早期に変性・石灰化し、椎間板ヘルニアリスクが上昇する。",
        "symptoms": "後肢のふらつき・痛み・歩行困難。重症例では完全麻痺。",
        "inheritance": "常染色体（不完全）優性。",
        "advice": "発症犬は階段・ジャンプの制限と体重管理。CDDY（CFA12）と異なる変異のため、検査結果は別個に解釈。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (IVDD Type I)", "url": _g("IVDD Type I FGF4 CFA12 犬")},
        ],
    },
    {
        "match": ["complement 3 deficiency", "c3 deficiency"],
        "title": "補体 C3 欠損症 (C3 Deficiency)",
        "summary": "補体経路中心因子 C3 の欠損による先天性免疫不全症。",
        "mechanism": "C3 遺伝子変異により補体活性化経路が破綻し、細菌感染への抵抗力が低下する。",
        "symptoms": "若齢期からの繰り返す細菌感染、肺炎、皮膚膿瘍。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は感染予防と早期治療。Brittany Spaniel 等で報告。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (C3 Deficiency)", "url": _g("補体C3欠損症 C3 犬")},
        ],
    },
    {
        "match": ["canine leukocyte adhesion deficiency", "clad i", "clad iii", "itgb2", "fermt3"],
        "title": "白血球接着不全症 (CLAD I/III / ITGB2, FERMT3)",
        "summary": "白血球表面の接着分子異常により細菌感染防御が著しく障害される重症免疫不全症。Setter・German Shepherd 等で報告。",
        "mechanism": "ITGB2（CLAD I）または FERMT3（CLAD III）遺伝子変異により白血球が血管壁から組織へ移行できない。",
        "symptoms": "新生子期からの繰り返す重症細菌感染、創傷治癒遅延。多くは早期死亡。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法は対症療法のみ。Setter・German Shepherd の繁殖前検査必須。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (CLAD)", "url": _g("白血球接着不全症 CLAD ITGB2 FERMT3 犬")},
        ],
    },
    {
        "match": ["multiple system degeneration", "msd", "serac1"],
        "title": "犬多系統変性症 (Canine Multiple System Degeneration / SERAC1)",
        "summary": "Chinese Crested・Kerry Blue Terrier で報告される、若齢発症の進行性多系統神経変性症。",
        "mechanism": "SERAC1 遺伝子変異によりミトコンドリア機能が障害され、複数の神経核が変性する。",
        "symptoms": "若齢期からの運動失調・歩行異常・進行性麻痺。",
        "inheritance": "常染色体劣性。",
        "advice": "対症療法のみ。Chinese Crested・Kerry Blue Terrier の繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Multi-System Degeneration)", "url": _g("Multiple System Degeneration SERAC1 犬")},
        ],
    },
    {
        "match": ["primary ciliary dyskinesia", "pcd", "nme5", "stk36", "ccdc39"],
        "title": "原発性繊毛運動不全症 (PCD)",
        "summary": "気道・耳管・精子尾部などの繊毛運動異常による多系統症候群。慢性呼吸器感染・中耳炎・不妊が三大症状。",
        "mechanism": "NME5 / STK36 / CCDC39 等の繊毛構成遺伝子変異により繊毛運動が異常化する。",
        "symptoms": "若齢期からの慢性鼻汁・気管支炎・中耳炎、内臓逆位、繁殖能力低下。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は慢性呼吸器感染への予防的抗菌薬・気道清拭。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (PCD)", "url": _g("原発性繊毛運動不全 PCD 犬")},
        ],
    },
    {
        "match": ["ligneous membranitis", "plg ", "リグニアス"],
        "title": "木質性膜炎 (Ligneous Membranitis / PLG)",
        "summary": "プラスミノーゲン欠損により粘膜表面に異常な線維素膜が形成される稀な疾患。",
        "mechanism": "PLG 遺伝子変異によりプラスミノーゲンが欠損し、フィブリン分解が障害され、粘膜表面に厚い線維素膜が沈着する。",
        "symptoms": "口腔・眼結膜・気管支等の粘膜に厚い偽膜形成。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は局所処置と対症療法。専門医での包括的管理が必要。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Ligneous)", "url": _g("Ligneous Membranitis PLG 犬")},
        ],
    },
    {
        "match": ["lundehund syndrome", "leprel1"],
        "title": "ルンデフント症候群 (Lundehund Syndrome / LEPREL1)",
        "summary": "Norwegian Lundehund 特有の重症消化器症候群（蛋白漏出性腸症・リンパ管拡張症等を含む）。",
        "mechanism": "LEPREL1 遺伝子変異によりコラーゲン水酸化酵素機能が低下し、消化管粘膜構造が異常化する。",
        "symptoms": "中年期からの慢性下痢・体重減少・低蛋白血症。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は低脂肪・低繊維食、ステロイド療法。Norwegian Lundehund ブリーダーの繁殖前検査推奨。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Lundehund Syndrome)", "url": _g("Lundehund Syndrome LEPREL1")},
        ],
    },
    {
        "match": ["shar-pei autoinflammatory disease", "spaid", "mtbp", "shar-pei fever"],
        "title": "シャー・ペイ自己炎症性疾患 (SPAID / MTBP / 家族性シャーペイ熱)",
        "summary": "Shar-Pei 特有の周期性発熱と関節炎を主徴とする自己炎症性疾患（FSF / Familial Shar-Pei Fever）。",
        "mechanism": "MTBP 遺伝子近傍の調節領域変異により IL-6 等の炎症性サイトカインが過剰産生される。",
        "symptoms": "周期的な発熱（39-41°C）、関節腫脹、長期的にアミロイドーシスを併発し腎不全に至るリスク。",
        "inheritance": "複雑（常染色体不完全優性）。",
        "advice": "発症犬は NSAIDs・コルチコステロイドで発作を管理。早期診断で長期予後改善。Shar-Pei ブリーダーは繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (SPAID)", "url": _g("Shar-Pei Fever SPAID MTBP")},
        ],
    },
    {
        "match": ["raine syndrome", "fam20c"],
        "title": "レイン症候群 (Raine Syndrome / FAM20C)",
        "summary": "Soft Coated Wheaten Terrier 等で報告される、全身骨硬化症の症候群。",
        "mechanism": "FAM20C 遺伝子変異により細胞外マトリックスタンパクのリン酸化が異常化し、骨石灰化過程が異常亢進する。",
        "symptoms": "頭蓋骨の異常な骨硬化、顔貌異常、新生子期から致死的になり得る。",
        "inheritance": "常染色体劣性。",
        "advice": "治療法なし。両親検査による発症犬出生回避が最重要。",
        "severity": "high",
        "references": [
            {"label": "詳細を検索 (Raine)", "url": _g("Raine Syndrome FAM20C")},
        ],
    },
    {
        "match": ["recurrent inflammatory pulmonary", "ripd", "akna"],
        "title": "繰り返す炎症性肺疾患 (RIPD / AKNA)",
        "summary": "Rough Collie 等で報告される、繰り返す肺の炎症性疾患。",
        "mechanism": "AKNA 遺伝子変異により肺の免疫制御機能が異常化する。",
        "symptoms": "若齢期からの慢性咳嗽、繰り返す肺炎、運動不耐性。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は予防的抗菌薬・抗炎症療法。Rough Collie の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (RIPD)", "url": _g("Recurrent Inflammatory Pulmonary Disease AKNA Rough Collie")},
        ],
    },
    {
        "match": ["deafness vestibular doberman", "dvdob", "dings", "myo7a"],
        "title": "ドーベルマン難聴・前庭症候群 (DVDob / DINGS / MYO7A)",
        "summary": "Doberman Pinscher 特有の若齢発症の難聴と前庭機能障害の症候群。",
        "mechanism": "MYO7A（ミオシン VIIA）遺伝子変異により内耳有毛細胞の機械感覚機能が障害される。",
        "symptoms": "若齢期からの両側性難聴、前庭機能障害による頭部傾斜・運動失調。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は視覚と振動を活用した訓練で生活可能。Doberman ブリーダーの繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (DVDob)", "url": _g("Doberman DVDob DINGS MYO7A")},
        ],
    },
    {
        "match": ["early bilateral deafness", "loxhd1"],
        "title": "若年両側性難聴 (Early Bilateral Deafness / LOXHD1)",
        "summary": "Rottweiler で報告される、若齢発症の両側性難聴。",
        "mechanism": "LOXHD1 遺伝子変異により内耳有毛細胞機能が障害される。",
        "symptoms": "若齢期からの両側性難聴。前庭機能は保たれる。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は視覚・振動を活用した訓練で生活可能。Rottweiler の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (LOXHD1 Deafness)", "url": _g("Rottweiler Early Bilateral Deafness LOXHD1")},
        ],
    },
    {
        "match": ["early onset adult deafness", "eoad", "eps8l2"],
        "title": "若齢成犬発症難聴 (EOAD / EPS8L2)",
        "summary": "Rhodesian Ridgeback 特有の若齢成犬発症難聴。",
        "mechanism": "EPS8L2 遺伝子変異により内耳有毛細胞構造が脆弱化する。",
        "symptoms": "若齢成犬期からの進行性難聴。",
        "inheritance": "常染色体劣性。",
        "advice": "Rhodesian Ridgeback の繁殖前検査推奨。発症犬は視覚訓練。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (EOAD)", "url": _g("Rhodesian Ridgeback EOAD EPS8L2")},
        ],
    },
    {
        "match": ["unilateral deafness vestibular", "uds", "ptprq"],
        "title": "片側性難聴 + 前庭症候群 (UDS / PTPRQ)",
        "summary": "Doberman で報告される、片側性難聴と前庭機能障害。",
        "mechanism": "PTPRQ 遺伝子変異により内耳有毛細胞機能が障害される。",
        "symptoms": "若齢期からの片側性難聴、頭部傾斜。",
        "inheritance": "常染色体劣性。",
        "advice": "Doberman の繁殖前検査推奨。発症犬は QOL 維持可能。",
        "severity": "low",
        "references": [
            {"label": "詳細を検索 (UDS PTPRQ)", "url": _g("Doberman Unilateral Deafness PTPRQ")},
        ],
    },
    {
        "match": ["cleft lip and palate", "adamts20", "口唇口蓋裂"],
        "title": "口唇口蓋裂 (Cleft Lip and Palate / ADAMTS20)",
        "summary": "Nova Scotia Duck Tolling Retriever で報告される、胎児期の口腔発達不全による先天性奇形。",
        "mechanism": "ADAMTS20 遺伝子変異により口蓋発達期の細胞接着・移動が障害される。",
        "symptoms": "出生時から明らかな口唇・口蓋の裂、哺乳困難、誤嚥性肺炎リスク。",
        "inheritance": "常染色体劣性。",
        "advice": "外科的修復で改善可能。Nova Scotia Duck Tolling Retriever の繁殖前検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (Cleft Lip ADAMTS20)", "url": _g("口唇口蓋裂 ADAMTS20 Toller")},
        ],
    },
    {
        "match": ["cleft palate cp1", "dlx6"],
        "title": "口蓋裂 CP1 (Cleft Palate / DLX6)",
        "summary": "Nova Scotia Duck Tolling Retriever で報告される、ADAMTS20 と異なる原因遺伝子による口蓋裂。",
        "mechanism": "DLX6 遺伝子変異により胎児期の口蓋形成が阻害される。",
        "symptoms": "出生時の口蓋裂、哺乳困難、誤嚥性肺炎リスク。",
        "inheritance": "常染色体劣性。",
        "advice": "外科的修復で改善可能。Toller の繁殖前検査では ADAMTS20 と併せて検査推奨。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (DLX6 Cleft Palate)", "url": _g("Cleft Palate CP1 DLX6 Toller")},
        ],
    },
    {
        "match": ["craniomandibular osteopathy", "cmo", "slc37a2"],
        "title": "頭蓋下顎骨症 (CMO / SLC37A2)",
        "summary": "若齢期に下顎骨・側頭骨に異常な骨増殖が起こる疾患。Terrier 系・Basset Hound 等で報告。",
        "mechanism": "SLC37A2 遺伝子変異により骨形成-吸収バランスが崩れ、下顎骨・側頭骨に過剰な骨形成が起こる。",
        "symptoms": "生後数か月からの開口困難、咀嚼時の痛み、発熱。",
        "inheritance": "常染色体劣性。",
        "advice": "発症犬は鎮痛薬・抗炎症療法で症状緩和。多くは思春期以降に自然軽快する。",
        "severity": "medium",
        "references": [
            {"label": "詳細を検索 (CMO)", "url": _g("頭蓋下顎骨症 CMO SLC37A2")},
        ],
    },
]
